[package]
name = "webstack"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
askama.workspace = true
askama_web.workspace = true
serde.workspace = true
rust-embed.workspace = true
tokio.workspace = true
tracing.workspace = true
webstack-core = { path = "../webstack-core" }
webstack-web = { path = "../webstack-web" }

[lints]
workspace = true
