[package]
name = "webstack-web"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
askama.workspace = true
axum.workspace = true
axum-login.workspace = true
axum-server.workspace = true
futures-util.workspace = true
mime_guess.workspace = true
rcgen.workspace = true
rust-embed.workspace = true
rustls-acme.workspace = true
serde.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tower-http.workspace = true
tower-sessions.workspace = true
tracing.workspace = true
turso.workspace = true
uuid.workspace = true
webstack-core = { path = "../webstack-core" }
webstack-db = { path = "../webstack-db" }
webstack-auth = { path = "../webstack-auth" }

[dev-dependencies]
reqwest.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tower.workspace = true

[lints]
workspace = true
